fix: Add relative location to jessie nodes
superfaceai/parser pull request #78
Opened 2021-11-05 19:18 UTC by martinalbert

## Description

Refactors location storing in validation issues.

## Motivation and Context

Weird behaviour in `language-vscode-client`.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTION_GUIDE** document.
- [x] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-11-09 10:27 UTC, lukas-valenta commented
pls don't merge until i look at it and create dev branch (thursday)

2021-11-15 07:54 UTC, lukas-valenta requested changes
looks good, fix the tests and it's good to go

2021-11-22 07:45 UTC, lukas-valenta approved these changes

2021-11-23 20:26 UTC, TheEdward162 approved these changes

2021-11-24 10:21 UTC, merged