fix(MapValidator): Validation of objects with dot notation
superfaceai/parser pull request #82
Opened 2021-11-10 19:30 UTC by martinalbert

## Description

Refactors handling variables that are written with dot notation, e.g. `output.is.nested = true`. 

## Motivation and Context

Wrong linter errors.

```
Map for profile: "address/geocoding" and provider: "nominatim" found on local filesystem

🆗 Parsing map file: /station/capabilities/address/geocoding/maps/nominatim.suma

⚠️ Validating profile: /station/capabilities/address/geocoding/profile.supr to map: /station/capabilities/address/geocoding/maps/nominatim.suma
ObjectLiteral - Wrong Object Structure: expected addressCountry, addressRegion, addressLocality, streetAddress, postalCode, formattedAddress, but got , , , , , , , , , , , 

```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTION_GUIDE** document.
- [x] I haven't repeated the code. (DRY)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-11-15 07:48 UTC, lukas-valenta requested changes
looks good, fix the tests and it's good to go

2021-11-19 08:00 UTC, lukas-valenta approved these changes

2021-11-19 08:02 UTC, lukas-valenta commented on src/interpreter/map-validator.test.ts
> +15:34 PrimitiveLiteral - Wrong Structure: expected number, but got "false"
i see now it's all one string, should be array of strings imo

2021-11-19 11:48 UTC, martinalbert commented on src/interpreter/map-validator.test.ts
> +15:34 PrimitiveLiteral - Wrong Structure: expected number, but got "false"
True, I'll let you know when it'll be ready

2021-11-19 13:37 UTC, martinalbert commented on src/interpreter/map-validator.test.ts
> +15:34 PrimitiveLiteral - Wrong Structure: expected number, but got "false"
@lukas-valenta check it out pls

2021-11-22 07:44 UTC, lukas-valenta approved these changes
Looks great :+1:

2021-11-22 08:36 UTC, lukas-valenta approved these changes

2021-11-22 16:08 UTC, merged